### ISSUE TITLE
大神，运行崩溃，package.json是不是该改改了？

### ISSUE THREAD

**Issue by LinDing** [airingursb/two-life#1]
版本是v1.2发布版
npm install
报告一个警告：
pm WARN EPEERINVALID react-native-calendars@1.2.22 requires a peer of react-native@0.44.0 but none was installed.

npm start
然后xcode打开项目，运行的时候报错，
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'i.ViewPropTypes.style')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'i.ViewPropT..., stack:

大神，package.json是不是该改改了？

**Comment by airingursb** [comment]
react-native-calendars前两天更新了，所以现在要锁定一下版本。

```
"react-native-calendars": "1.2.21"
```

已解决，谢谢你的反馈。
