### ISSUE TITLE
Undefined is not an object (evaluating '_reactNative.ViewPropTypes.style') 

### ISSUE THREAD

**Issue by flyher** [airingursb/two-life#18]
```shell
npm install
react-native run-android
react-native start
```
客户端红屏报出标题的错误.

看到这里同样有这个错误,尝试更换了rn版本,好像也不行.
https://github.com/GeekyAnts/NativeBase/issues/851

**Comment by airingursb** [comment]
@flyher react-native-snap-carousel 这个组件的问题，`npm i`之后，把它源代码中的两处`ViewPropTypes`删除即可

**Comment by flyher** [comment]
@airingursb 
非常感谢。
代码质量比较好，这个项目让我受益匪浅，学习到不少rn的用法！

**Comment by airingursb** [comment]
@flyher 代码质量还有待提高哈…准备这个月底重构一下。
如果想学习的话，推荐阅读我们项目组前端妹子写的代码：[1ibarary/1ibrary-front-end](https://github.com/1ibrary/1ibrary-front-end)

**Comment by flyher** [comment]
@airingursb 
感谢，已fork，准备有时间看看。
